### ISSUE TITLE
ModuleNotFoundError: No module named 'ctbRA'

### ISSUE THREAD

**Issue by Anto007** [christophertbrown/fix_assembly_errors#3]
I get the below error when I try to run the ra2.py script. Also is it ok if I leave out shrinksam (difficulty in getting the tool installed and no support from the developer) and modify the bowtie2 command-line to include the --no-unal flag. If I'm not mistaken, this will circumvent the need to use shrinksam? Many thanks for your kind help!

(virtualenv3) user@XXXX:~/tools/fix_assembly_errors/ctbRA$ ./ra2.py 
Traceback (most recent call last):
  File "./ra2.py", line 36, in <module>
    from ctbRA.assemble import velvet as velvet
ModuleNotFoundError: No module named 'ctbRA'

**Comment by Anto007** [comment]
Oops missed to do 'python setup.py install'; the error disappeared after I did this!

**Comment by Anto007** [comment]
Now I get this below new error (I'm using python version 3.6.2; is the error related to it?):
(virtualenv3) user@XXXXX:~/tools/fix_assembly_errors/ctbRA$ ./ra2.py -i contigs.fasta -1 read_1.fastq.gz -2 read_2.fastq.gz 
Building a SMALL index
Traceback (most recent call last):
  File "./ra2.py", line 1119, in <module>
    window = window)
  File "./ra2.py", line 975, in curate_assembly
    allow_orphan = False, allow_orphan_ends = False, save_mapping = save_mapping)
  File "./ra2.py", line 915, in check_assembly
    mapping, pr_split = map_reads(assembly, scaffolds, pr, threads, multiple, pr_split = pr_split)
  File "./ra2.py", line 86, in map_reads
    return run_bowtie(assembly, sam, pr, pr_split, sr, threads, multiple, bt_dir) # run bowtie, return sam file
  File "./ra2.py", line 66, in run_bowtie
    % (matches_command, threads, bt_dir, assembly.rsplit('/', 1)[-1], pr_command, sr_command, sam)\
TypeError: not all arguments converted during string formatting
